#!/usr/bin/env python3

from sortd.lib import sig_trap
from sortd.s_cfg import dump_ini, load_ini


def main() -> None:
    ini = load_ini()
    dump_ini(ini)


try:
    sig_trap()
    main()
except KeyboardInterrupt:
    exit(130)
except BrokenPipeError:
    exit(13)
