#!/usr/bin/env python3

from sortd.lib import sig_trap
from sortd.s_cfg import dump_cfg, load_cfg


def main() -> None:
    cfg = load_cfg()
    dump_cfg(cfg)


try:
    sig_trap()
    main()
except KeyboardInterrupt:
    exit(130)
except BrokenPipeError:
    exit(13)
