#!/usr/bin/env python3

from argparse import ArgumentParser, Namespace

from sortd.lib import sig_trap
from sortd.s_json import dump_json, load_json


def parse_args() -> Namespace:
    parser = ArgumentParser()
    parser.add_argument("-i", "--indent", type=int, default=2)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    json = load_json()
    dump_json(json, indent=args.indent)


try:
    sig_trap()
    main()
except KeyboardInterrupt:
    exit(130)
except BrokenPipeError:
    exit(13)
