#!/usr/bin/env python3

from locale import strxfrm
from signal import SIG_DFL, SIGPIPE, signal
from sys import stderr, stdin, stdout
from typing import Any

from toml import dump, loads
from toml.decoder import TomlDecodeError


def recur_sort(data: Any) -> Any:
    if type(data) is dict:
        return {k: recur_sort(data[k]) for k in sorted(data, key=strxfrm)}
    elif type(data) is list:
        return [recur_sort(el) for el in data]
    else:
        return data


def main() -> None:
    data = stdin.read()
    try:
        toml = loads(data)
    except TomlDecodeError:
        print(f"ERROR! -- Failed to parse:\n\n{data}", file=stderr)
        exit(1)
    else:
        new = recur_sort(toml)
        dump(new, stdout)


try:
    signal(SIGPIPE, SIG_DFL)
    main()
except KeyboardInterrupt:
    exit(130)
