#!/usr/bin/env python3

from argparse import ArgumentParser, Namespace
from shutil import get_terminal_size

from sortd.lib import sig_trap
from sortd.s_yaml import dump_yaml, load_yaml


def parse_args() -> Namespace:
    cols, _ = get_terminal_size((80, -1))
    parser = ArgumentParser()
    parser.add_argument("-i", "--indent", type=int, default=2)
    parser.add_argument("-w", "--width", type=int, default=cols)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    yaml = load_yaml()
    dump_yaml(yaml, width=args.width, indent=args.indent)


try:
    sig_trap()
    main()
except KeyboardInterrupt:
    exit(130)
except BrokenPipeError:
    exit(13)
