---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_ver }}

      - run: |-
          pip install -- tomli

      - shell: python
        run: |-
          from itertools import chain
          from os import execl
          from sys import executable

          from tomli import load

          with open("pyproject.toml", "rb") as fd:
              toml = load(fd)
          project = toml["project"]
          execl(
              executable,
              executable,
              "-m",
              "pip",
              "install",
              "--upgrade",
              "--",
              *project["dependencies"],
              *chain.from_iterable(project["optional-dependencies"].values()),
          )

      - run: |-
          mypy -- .
