---
name: Release

on:
  push:
    paths:
      - "setup.py"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install -U setuptools wheel

      - name: Build
        run: python3 setup.py sdist bdist_wheel

      - name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
