---
name: Release

on:
  push:
    paths:
      - "pyproject.toml"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - run: |-
          pip install -- tomli setuptools

      - shell: python
        run: |-
          from itertools import chain
          from os import execl
          from sys import executable

          from tomli import load

          with open("pyproject.toml", "rb") as fd:
              toml = load(fd)
          project = toml["project"]
          execl(
              executable,
              executable,
              "-m",
              "pip",
              "install",
              "--upgrade",
              "--",
              *project["dependencies"],
              *chain.from_iterable(project["optional-dependencies"].values()),
          )

      - run: |-
          mypy -- .

      - shell: python
        run: |-
          from setuptools import setup
          from sys import argv
          argv.extend(("sdist", "bdist_wheel"))
          setup()

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
